# Слушаем стандартный порт MQTT (для бэкенда или десктопных клиентов)
listener 1883
allow_anonymous true

# Слушаем порт для WebSockets (для браузерного фронтенда)
listener 9001
protocol websockets
allow_anonymous true