events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # ОТКЛЮЧАЕМ КЭШИРОВАНИЕ ЯДРА ДЛЯ СТАТИКИ
    sendfile off;

    server {
        # Слушаем стандартный 80-й порт (HTTP)
        listen 80;
        
        # Указываем ваш домен (и с www, и без)
        server_name icq.works www.icq.works;

        # 1. Раздаем фронтенд (наш index.html)
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # 2. Прокидываем WebSockets для MQTT-чата
        location /mqtt {
            proxy_pass http://mosquitto:9001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            
            # Важно для стабильности вебсокетов, чтобы Nginx не рвал соединение при простое
            proxy_read_timeout 86400;
        }
    }
}